const REWARD_CONFIG = Object.freeze({
	POINTS_PER_PKR: 20,
	DAILY_CHECKIN_POINTS: 10,
	QUIZ_POINTS: 20,
	GAME_REWARD_INTERVAL_MINUTES: 5,
	GAME_REWARD_POINTS: 15,
	LUCKY_SPIN_MIN_POINTS: 1,
	LUCKY_SPIN_MAX_POINTS: 10,
	REFERRAL_REWARD_POINTS: 100,
	REFERRAL_REQUIRED_COMPLETIONS: 2,
	TOURNAMENT_RANK_1_POINTS: 500,
	TOURNAMENT_RANK_2_POINTS: 300,
	TOURNAMENT_RANK_3_POINTS: 100,
	MIN_WITHDRAWAL_POINTS: 1000,
})

module.exports = { REWARD_CONFIG }
